python CorrelationAnlysis.py ./bleu/gs-clickedresult-df+oc-clickedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-clickedresult-df+oc-clickedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-clickedresult-df+oc-fixedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-clickedresult-df+oc-fixedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-clickedresult-df+oc-useranswer.bleu
python CorrelationAnlysis.py ./bleu/gs-clickedresult-ndf+oc-clickedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-clickedresult-ndf+oc-clickedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-clickedresult-ndf+oc-fixedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-clickedresult-ndf+oc-fixedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-clickedresult-ndf+oc-useranswer.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-df+oc-clickedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-df+oc-clickedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-df+oc-fixedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-df+oc-fixedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-df+oc-useranswer.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-ndf+oc-clickedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-ndf+oc-clickedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-ndf+oc-fixedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-ndf+oc-fixedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-fixedresult-ndf+oc-useranswer.bleu
python CorrelationAnlysis.py ./bleu/gs-manual+oc-clickedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-manual+oc-clickedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-manual+oc-fixedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-manual+oc-fixedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-manual+oc-useranswer.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-df+oc-clickedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-df+oc-clickedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-df+oc-fixedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-df+oc-fixedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-df+oc-useranswer.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-ndf+oc-clickedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-ndf+oc-clickedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-ndf+oc-fixedresult-df.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-ndf+oc-fixedresult-ndf.bleu
python CorrelationAnlysis.py ./bleu/gs-useranswer-ndf+oc-useranswer.bleu
